apiVersion: v1
kind: Namespace
metadata:
  name: lethicia-andrade


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lethicia-teste
  namespace: lethicia-andrade
  labels:
    app: lethicia
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: lethicia
  replicas: 1
  template:
    metadata:
      labels:
        app: lethicia
    spec:
      containers:
      - image: lethiciahas/my-image
        name: nginx-lethicia

---

apiVersion: v1
kind: Service
metadata:
  name: lethicia-andrade
  namespace: lethicia-andrade
spec:
  selector:
     app: lethicia
  ports:
  - port: 80
    targetPort: 80

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lethicia-test
  namespace: lethicia-andrade

spec:
  ingressClassName: nginx
  rules:
  - host: lethicia-andrade.stag.jac.bsb.br
    http:
      paths:
      - backend:
          service:
            name: lethicia-andrade
            port:
              number: 80
        path: /
        pathType: Prefix
